import json
import logging

logger = logging.getLogger(__name__)


async def handle_draft_generate(msg, js):
    """Placeholder draft generation handler. Produces a template markdown draft."""
    from worker.app.services.storage import upload_object

    try:
        envelope = json.loads(msg.data.decode())
        payload = envelope["payload"]
        job_id = envelope["job_id"]
        workspace_id = envelope["workspace_id"]

        draft_id = payload["draft_id"]
        incident_id = payload.get("incident_id", "unknown")
        title = payload.get("title", "Untitled Draft")

        logger.info("draft.generate job=%s draft=%s", job_id, draft_id)

        # Generate template draft body in markdown
        draft_body = f"""# {title}

## Incident Reference
- Incident ID: {incident_id}
- Workspace: {workspace_id}

## Summary
[Placeholder: AI-generated summary will appear here]

## Timeline of Events
[Placeholder: Chronological timeline will be populated from evidence]

## Evidence Overview
[Placeholder: List of supporting evidence items]

## Analysis
[Placeholder: Detailed analysis and findings]

## Recommendations
[Placeholder: Recommended actions and next steps]

---
**Status:** needs_review
**Draft ID:** {draft_id}
**Generated by:** BCC worker draft pipeline
"""

        # Store draft in MinIO
        draft_key = f"{workspace_id}/drafts/{draft_id}/draft.md"
        upload_object("drafts", draft_key, draft_body.encode("utf-8"), "text/markdown")

        logger.info("Stored draft at drafts/%s", draft_key)

        await msg.ack()
        logger.info("draft.generate completed job=%s", job_id)

    except Exception:
        logger.exception("draft.generate failed")
        await msg.nak()
