import hashlib
import io
import json
import logging
import zipfile

logger = logging.getLogger(__name__)


async def handle_export_packet(msg, js):
    """Placeholder export handler. Creates a minimal ZIP with README and hash manifest."""
    from worker.app.services.storage import upload_object

    try:
        envelope = json.loads(msg.data.decode())
        payload = envelope["payload"]
        job_id = envelope["job_id"]
        workspace_id = envelope["workspace_id"]

        packet_id = payload["packet_id"]
        packet_name = payload.get("packet_name", f"packet-{packet_id}")

        logger.info("export.packet job=%s packet=%s", job_id, packet_id)

        # Build minimal ZIP in memory
        zip_buffer = io.BytesIO()
        manifest_entries = {}

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # README
            readme_content = (
                f"# Export Packet: {packet_name}\n\n"
                f"Packet ID: {packet_id}\n"
                f"Workspace: {workspace_id}\n"
                f"Generated by BCC worker export pipeline.\n"
            )
            zf.writestr("README.md", readme_content)
            manifest_entries["README.md"] = hashlib.sha256(
                readme_content.encode("utf-8")
            ).hexdigest()

            # Hash manifest
            manifest_json = json.dumps(manifest_entries, indent=2)
            zf.writestr("hash_manifest.json", manifest_json)

        zip_bytes = zip_buffer.getvalue()

        # Upload to MinIO exports bucket
        export_key = f"{workspace_id}/{packet_id}/{packet_name}.zip"
        upload_object("exports", export_key, zip_bytes, "application/zip")

        logger.info("Uploaded export packet to exports/%s", export_key)

        await msg.ack()
        logger.info("export.packet completed job=%s", job_id)

    except Exception:
        logger.exception("export.packet failed")
        await msg.nak()
